# ==========================================================================
# VENDORED COPY -- DO NOT EDIT THIS FILE.
#
# Canonical source:
#     D:\workspace\projects\job-hunting\mcp-servers\jobcore\src\jobcore\buildinfo.py
# Vendored from jobcore commit: 998baf1
#
# WHY A COPY AND NOT A DEPENDENCY. This server does not depend on jobcore and
# must not start. Adding the dependency for a debug field would turn
# "pip install -r requirements.txt" into "also clone a sibling repo", and this
# package's dependency discipline (every pin in requirements.txt carries a
# written justification, and a test enforces the fastmcp upper bound) exists
# to keep that from happening quietly. jobcore's own pyproject declares zero
# runtime dependencies precisely so that servers outside its dependency tree
# can vendor a module instead: pure stdlib, nothing to inherit.
#
# THE BODY BELOW IS VERBATIM. Not a port, not a subset, not "mostly the same".
# tests/test_vendored_buildinfo.py locates the canonical file by walking up
# from the test to the mcp-servers directory, strips exactly this header, and
# fails if a single byte differs. Fix bugs UPSTREAM in jobcore, then re-vendor
# and move the commit line above; editing this copy in place is the drift the
# test exists to catch.
# --- END VENDOR HEADER; everything below is verbatim from jobcore ---
"""What code is actually running -- resolved once, at import, and then frozen.

A fix committed to disk changes nothing for a process that is already up. On
2026-08-21 that cost real time: a bug was diagnosed as a regression and an agent
was dispatched to re-fix it, and the correction came back that the fix was
already on disk and the *process* was stale. The same class recurred three more
times that day. Every check available at the time was a behavioural fingerprint
-- does this field appear, is that count right -- because there was no way to ask
a server what code it holds.

This module is that way. A server calls :func:`stamp` ONCE at import and puts
the result in its ``*_server_info`` payload.

**The freeze is the whole point, not a performance note.** A per-call
``git rev-parse`` run from a stale process reports the NEW commit sitting on
disk, which is worse than reporting nothing: it reads as confirmation that the
fix is loaded, and the thing it confirms is false. So :func:`stamp` memoises on
the first call and every later call returns that same frozen object without
touching git. ``tests/test_buildinfo.py`` proves it by committing to a real
temporary repository *after* the first call and asserting the stamp still names
the old commit.

**Unknown is a value, never a guess.** No git executable, no work tree, a
repository with no commits yet, a git that hangs -- each returns
``source="unknown"`` with ``detail`` saying which, and ``commit=None``. A
plausible-looking hash that nobody measured is the failure this module exists
to prevent, so there is no fallback that invents one.

**Nothing here may break server import.** Every git call is bounded by
:data:`GIT_TIMEOUT_SECONDS` and every exception is caught and turned into an
``unknown`` stamp, because this runs at module import of a server whose actual
job is something else.

Pure stdlib, like the rest of jobcore. Servers that do not depend on jobcore
(linkedin, ats-jobs) vendor a copy rather than acquiring a cross-repo sibling
install for a debug field; this module is the canonical version and a vendored
copy says so in its header.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import threading
import time
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Optional

__all__ = [
    "BuildStamp",
    "ProcessClock",
    "self_stamp",
    "GIT_TIMEOUT_SECONDS",
    "SHORT_HASH_LENGTH",
    "resolve",
    "stamp",
    "invalidate_cache",
]

#: Per-git-invocation budget. This runs during a server's import, so a hung git
#: (a network-mounted repo, a stuck index.lock, an antivirus scan) must degrade
#: to "unknown" rather than hold the whole server at the import line.
GIT_TIMEOUT_SECONDS = 5.0

#: Twelve is unambiguous in any repository this family will ever have and is
#: short enough to read aloud when comparing two servers.
SHORT_HASH_LENGTH = 12


@dataclass(frozen=True)
class BuildStamp:
    """The commit a process was started from. Frozen: it describes the past.

    ``resolved_at`` is not decoration -- it is the field that makes the stamp
    falsifiable. A stamp whose ``resolved_at`` is hours old and whose ``commit``
    matches ``git rev-parse HEAD`` on disk means the running code IS current. A
    stamp whose ``commit`` differs from disk means the process is stale and no
    amount of committing will change its behaviour until it is restarted.
    """

    commit: Optional[str] = None
    commit_full: Optional[str] = None
    branch: Optional[str] = None
    committed_at: Optional[str] = None
    dirty: Optional[bool] = None
    dirty_files: Optional[int] = None
    version: Optional[str] = None
    resolved_at: str = ""
    source: str = "unknown"
    detail: Optional[str] = None

    def as_dict(self) -> dict:
        """A plain dict for a tool payload. Key order is the reading order."""
        return asdict(self)


class ProcessClock:
    """When this process came up, and how long it has been up.

    Split from :class:`BuildStamp` because the two answer different questions
    and have different lifetimes: the stamp is frozen at import and never moves,
    while uptime is derived fresh on every call. Keeping uptime *out* of the
    frozen stamp is deliberate -- a cached uptime is a lie that grows.

    ``started_at`` is the moment this module recorded the server's import. For
    a stdio MCP server, whose whole module tree is imported at startup, that is
    process start to within milliseconds. It is named for what it measures
    rather than for what it approximates, because there is no cross-platform
    stdlib way to read a real process creation time and a field called
    ``process_start_time`` that is actually an import time is exactly the
    "a number that means something else" defect this sweep exists to close.
    """

    def __init__(self) -> None:
        self.started_at = datetime.now(timezone.utc).isoformat()
        self._monotonic = time.monotonic()
        self.pid = os.getpid()

    def uptime_seconds(self) -> float:
        return round(time.monotonic() - self._monotonic, 1)

    def as_dict(self) -> dict:
        return {
            "pid": self.pid,
            "started_at": self.started_at,
            "uptime_seconds": self.uptime_seconds(),
        }


def _git_dir(start: Any) -> Optional[Path]:
    """The directory to run git in: ``start`` itself, or its parent if a file."""
    try:
        p = Path(start).resolve()
    except (OSError, ValueError, TypeError):
        return None
    return p if p.is_dir() else p.parent


def _run_git(cwd: Path, *args: str) -> Optional[str]:
    """One bounded git call. ``None`` on any failure, never an exception."""
    try:
        proc = subprocess.run(
            ["git", "-C", str(cwd), *args],
            capture_output=True,
            text=True,
            timeout=GIT_TIMEOUT_SECONDS,
            # Windows: keep a console window from flashing when a GUI-launched
            # client imports the server.
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
    except (OSError, subprocess.SubprocessError, ValueError):
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout


def _installed_version(distribution: Optional[str]) -> Optional[str]:
    """The version of an INSTALLED distribution, or ``None``.

    Not a guess and not a fallback for git: a different, real fact about a
    different situation. A dependency installed from a wheel or a git URL has
    no work tree to interrogate, so "which commit" has no answer there -- but
    "which release" does, and it is the answer that identifies the code.
    """
    if not distribution:
        return None
    try:
        from importlib.metadata import PackageNotFoundError, version

        return version(distribution)
    except Exception:
        return None


def resolve(start: Any, distribution: Optional[str] = None) -> BuildStamp:
    """Read the working tree's git state NOW. Not memoised -- see :func:`stamp`.

    Public because it is the honest counterpart in the staleness test: compare
    a held :func:`stamp` against a fresh :func:`resolve` and a stale process is
    visible as a disagreement. Servers should not call it on a request path.

    ``distribution`` names the installed package this path belongs to, and it
    is what keeps the answer useful off a developer box. CI found the hole on
    2026-08-22: a consumer installs jobcore from a git URL into site-packages,
    which is NOT a work tree, so the stamp was correctly ``unknown`` and
    therefore useless in exactly the deployment the hosting plan targets. With
    a distribution name the same call reports ``source="package"`` and the
    installed version. The name is REQUIRED rather than inferred from the path,
    because mapping a file back to the distribution that shipped it is a guess
    and this module does not guess.
    """
    now = datetime.now(timezone.utc).isoformat()

    def unknown(detail: str) -> BuildStamp:
        """No git answer. Report the installed version if there is one."""
        ver = _installed_version(distribution)
        if ver is not None:
            return BuildStamp(
                version=ver,
                resolved_at=now,
                source="package",
                detail="%s; reporting the installed %s version instead"
                % (detail, distribution),
            )
        return BuildStamp(resolved_at=now, source="unknown", detail=detail)

    cwd = _git_dir(start)
    if cwd is None:
        return unknown("could not resolve a directory from the given start path")
    if shutil.which("git") is None:
        return unknown("no git executable on PATH")

    # %H full hash, %cI committer date in strict ISO 8601. One call, and it is
    # also the existence check: it fails on a non-repository and on a repository
    # with no commits, which are different `detail` answers below.
    head = _run_git(cwd, "show", "-s", "--format=%H%n%cI", "HEAD")
    if not head:
        inside = _run_git(cwd, "rev-parse", "--is-inside-work-tree")
        if not inside or inside.strip() != "true":
            return unknown("not inside a git work tree")
        return unknown("git work tree has no commits yet")

    lines = head.strip().splitlines()
    commit_full = lines[0].strip() if lines else ""
    committed_at = lines[1].strip() if len(lines) > 1 else None
    if not commit_full:
        return unknown("git returned an empty HEAD hash")

    branch_out = _run_git(cwd, "rev-parse", "--abbrev-ref", "HEAD")
    branch = branch_out.strip() if branch_out else None
    if branch == "HEAD":  # detached; the hash is the identity, not a name
        branch = None

    # Untracked files COUNT as dirty. The question this field answers is "does
    # the loaded code differ from that commit", and a new, untracked, imported
    # module differs from it just as much as an edited tracked one does. The
    # count is reported alongside so "dirty" can be judged rather than feared.
    status = _run_git(cwd, "status", "--porcelain")
    if status is None:
        dirty: Optional[bool] = None
        dirty_files: Optional[int] = None
        detail: Optional[str] = "git status failed; dirtiness unknown"
    else:
        entries = [line for line in status.splitlines() if line.strip()]
        dirty = bool(entries)
        dirty_files = len(entries)
        detail = None

    return BuildStamp(
        commit=commit_full[:SHORT_HASH_LENGTH],
        commit_full=commit_full,
        branch=branch,
        committed_at=committed_at,
        dirty=dirty,
        dirty_files=dirty_files,
        version=_installed_version(distribution),
        resolved_at=now,
        source="git",
        detail=detail,
    )


_CACHE: dict[str, BuildStamp] = {}
_CACHE_LOCK = threading.Lock()


def stamp(start: Any, distribution: Optional[str] = None) -> BuildStamp:
    """The import-time stamp for ``start``'s repository. Resolved at most once.

    THE CONTRACT: the first call shells out to git; every later call for the
    same ``start`` returns that first result and touches nothing. A commit made
    after the first call does not change what comes back, which is the whole
    reason this function exists rather than servers calling :func:`resolve`.

    Call it once, at module import, and hold the result in a module constant.
    Calling it per request is harmless but pointless -- the answer is frozen.
    """
    try:
        key = str(Path(start).resolve())
    except (OSError, ValueError, TypeError):
        key = repr(start)
    # The distribution is part of the identity: the same path asked with and
    # without one has two different right answers off a developer box.
    key = "%s#%s" % (key, distribution or "")
    cached = _CACHE.get(key)
    if cached is not None:
        return cached
    with _CACHE_LOCK:
        cached = _CACHE.get(key)
        if cached is not None:
            return cached
        try:
            result = resolve(start, distribution)
        except Exception as exc:  # pragma: no cover - resolve catches its own
            result = BuildStamp(
                resolved_at=datetime.now(timezone.utc).isoformat(),
                source="unknown",
                detail="build stamp resolution raised %s" % type(exc).__name__,
            )
        _CACHE[key] = result
        return result


def self_stamp() -> BuildStamp:
    """jobcore's own stamp, correct in BOTH of the ways it gets installed.

    A consumer that hardcodes ``stamp(jobcore.__file__)`` gets a useful answer
    on the operator's box, where jobcore is an editable install from a sibling
    checkout, and ``unknown`` everywhere else -- which is how a version echo
    ends up silent in the only environment where nobody can just run
    ``git log``. Call this instead.
    """
    return stamp(__file__, distribution="jobcore")


def invalidate_cache() -> None:
    """Drop the memo. For TESTS ONLY.

    A server that calls this has reintroduced the exact defect the module
    prevents: the next :func:`stamp` would report the commit on disk from a
    process still running the old one.
    """
    with _CACHE_LOCK:
        _CACHE.clear()


def build_block(
    start: Any,
    *,
    clock: Optional[ProcessClock] = None,
    extra: Optional[Mapping[str, Any]] = None,
) -> dict:
    """The ready-made ``build`` block for a ``*_server_info`` payload.

    Combines the frozen commit stamp with live process timing, so a reader gets
    both halves of "what is running here" in one place: which code, and since
    when. ``extra`` merges in whatever else the caller can pin -- a second
    repository's stamp, a config hash -- without each server re-inventing the
    key names.
    """
    block: dict = {"code": stamp(start).as_dict()}
    if clock is not None:
        block["process"] = clock.as_dict()
    if extra:
        block.update(dict(extra))
    return block
