# ==========================================================================
# VENDORED COPY -- DO NOT EDIT THIS FILE.
#
# Canonical source:
#     D:\workspace\projects\job-hunting\mcp-servers\jobcore\src\jobcore\paths.py
# Vendored from jobcore commit: b2f5d16
#
# WHY A COPY AND NOT A DEPENDENCY. This server does not depend on jobcore and
# must not start. Adding the dependency for a path-rendering helper would turn
# "pip install -r requirements.txt" into "also clone a sibling repo", and this
# package's dependency discipline (every pin in requirements.txt carries a
# written justification, and a test enforces the fastmcp upper bound) exists
# to keep that from happening quietly. jobcore's own pyproject declares zero
# runtime dependencies precisely so that servers outside its dependency tree
# can vendor a module instead: pure stdlib, nothing to inherit.
#
# THE BODY BELOW IS VERBATIM. Not a port, not a subset, not "mostly the same".
# tests/test_vendored_buildinfo.py locates the canonical file by walking up
# from the test to the mcp-servers directory, strips exactly this header, and
# fails if a single byte differs. Fix bugs UPSTREAM in jobcore, then re-vendor
# and move the commit line above; editing this copy in place is the drift the
# test exists to catch.
# --- END VENDOR HEADER; everything below is verbatim from jobcore ---
"""Paths a caller can act on, that are not this machine's absolute layout.

A live sweep on 2026-08-20 found ``D:\\<given-name>\\projects\\...`` inside MCP tool
results. That is wrong twice over: it publishes the machine's directory layout
into any shared transcript or future public release, and it is paid for in
tokens on every response that carries it.

The obvious fix -- delete the field -- trades one defect for another. "Where is
the config file even?" is a documented, real use of these tools, and a ``null``
where a path used to be is the same "a field that answers a different question
than it looks like" defect the rest of this sweep is closing. So paths are
RELATIVISED rather than removed: leak-free, and still an answer.

Three forms, in order, and the third one exists because CI caught the second
being insufficient:

1. **Relative to an anchor** -- the checkout root -- so
   ``<root>/../../config/jobhunt.json`` reads ``../../config/jobhunt.json``.
2. **Home-anchored** ``~/...`` for anything outside the checkout but under the
   user's home.
3. **The tail**, ``.../a/b/c``, for anything under neither.

Form 3 was added on 2026-08-21 after a Linux CI runner failed a test that
passed on every Windows box. The old last resort was the bare basename, which
collapses every entry of a "paths I searched" list to the identical string
``jobhunt.json`` -- strictly worse than saying nothing. On Windows a temp dir
lives under the user's home, so form 2 always caught it and the fallback never
fired locally; on the runner ``/tmp`` is under neither anchor, so every path
fell through. The test was right and the function was wrong.

All three forms survive a downstream drive-letter scrubber untouched: none
carries a drive letter, and the tail form deliberately carries no leading
slash either.

This is the canonical implementation. ``naukri_server/policy.display_path``
calls it with the naukri checkout as anchor; servers outside the jobcore
dependency (linkedin, ats-jobs) vendor a copy whose header says so.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Optional

__all__ = [
    "DISPLAY_TAIL_PARTS",
    "MAX_PARENT_HOPS",
    "display_path",
    "relativise_known",
]

#: Components kept by the tail form. Three is enough to tell two pytest tmp
#: dirs apart -- the case that exposed the old basename fallback -- and short
#: enough to publish no useful layout.
DISPLAY_TAIL_PARTS = 3

#: How far above the anchor a path may sit and still be shown anchor-relative.
#: The shared ``config/jobhunt.json`` lives two levels up from a server
#: checkout, so a bound below 2 would push the common case into form 2 or 3.
#: Beyond four hops the relative form stops being more readable than the tail.
MAX_PARENT_HOPS = 4


def display_path(raw: Any, *, anchor: Any, home: Optional[Any] = None) -> Optional[str]:
    """Render ``raw`` in the first of the three forms that applies.

    Args:
        raw: the path to render. ``None`` and ``""`` pass straight through, so
            "no file was found" stays distinguishable from "a file at /".
        anchor: the checkout root to measure against -- the caller's repository,
            not jobcore's. jobcore cannot know where its consumer lives, and a
            path relative to the *library* would be meaningless to the reader.
        home: override for the user's home directory. Tests pass it; callers
            should not.

    Returns:
        A string with no drive letter and no absolute root, or ``raw`` unchanged
        when it was falsy.
    """
    if not raw:
        return raw
    p = Path(raw)
    home_dir = Path(home) if home is not None else Path.home()

    try:
        rel = os.path.relpath(p, Path(anchor))
        # Count PARTS equal to "..", not occurrences of the substring: a
        # directory legitimately named "a..b" is not four levels up.
        if sum(1 for part in rel.split(os.sep) if part == os.pardir) <= MAX_PARENT_HOPS:
            return rel.replace(os.sep, "/")
    except (ValueError, OSError):
        pass

    try:
        return "~/" + p.relative_to(home_dir).as_posix()
    except (ValueError, OSError):
        pass

    # Drop the anchor ("C:\\", "/") so no drive letter or root can survive,
    # then keep the tail. One component means there is nothing to elide and the
    # "..." marker would be a lie, so it is omitted in that case.
    parts = p.parts[1:] if p.anchor else p.parts
    if len(parts) <= 1:
        return p.name
    tail = parts[-DISPLAY_TAIL_PARTS:]
    prefix = ".../" if len(tail) < len(parts) else ""
    return prefix + "/".join(tail)


def _spellings(raw: str) -> list:
    """Every way this path can be SPELLED in a message. Not a pattern -- a list.

    ``OSError.__str__`` renders its filename through ``repr()``, so a Windows
    path arrives in an error message with DOUBLED separators::

        str(OSError(13, "Permission denied", r"D:\a\b.json"))
        -> "[Errno 13] Permission denied: 'D:\\a\\b.json'"

    An exact-substring scrubber looking for the single-separator form finds
    nothing there and passes the message through as clean. Measured live by the
    uplers slice on 2026-08-22: one unreadable ``jobhunt.json`` produced a
    single sentence whose two halves got opposite verdicts -- the ``{path}``
    half correctly relativised, the ``{exc}`` half publishing the full layout,
    from tools that render no path field at all.

    This stays a SPELLING list rather than becoming a path-shaped-text hunt.
    The exactness is the safety property: a heuristic would eventually eat a
    URL or an API route and do more damage than the leak. On POSIX the two
    spellings are identical, so this costs and adds nothing there.
    """
    doubled = raw.replace("\\", "\\\\")
    return [raw] if doubled == raw else [raw, doubled]


def relativise_known(text: Any, *, known, render) -> Any:
    """Replace each KNOWN absolute path found inside ``text`` with its rendering.

    Renaming a field is not enough when the path was baked into prose. This
    module's loader composes messages like ``f"{path} is not valid JSON: {exc}"``
    and ``f"cannot read {path}: {exc}"``; those strings reach a caller through
    ``config_error``, through ``config_status``, and -- found live on 2026-08-22
    -- through the per-call notes that every scoring tool appends, so one
    unparseable config file published the machine's layout from tools that
    render no path of their own.

    SUBSTITUTION IS EXACT, NEVER HEURISTIC. Only strings the caller already
    KNOWS to be paths are replaced. A regex that hunted for path-shaped text in
    arbitrary prose would eventually eat a Naukri API route, a URL, or a
    Windows drive letter inside quoted user content -- which is how a scrubber
    does more damage than the leak it was written for.

    Args:
        text: any value. Non-strings are returned untouched, so this is safe to
            map over a whole payload.
        known: the path strings this caller knows it may have emitted, e.g. a
            config snapshot's ``source`` and every entry of ``searched``.
        render: how to display one path, normally
            ``lambda p: display_path(p, anchor=...)``.

    Returns:
        ``text`` with each known path substituted; the same object when nothing
        matched.
    """
    if not isinstance(text, str) or not text:
        return text
    pairs = []
    for raw in {str(k) for k in known if k}:
        rendered = str(render(raw))
        for spelling in _spellings(raw):
            pairs.append((spelling, rendered))
    # Longest first: one searched path is often a prefix of another, and
    # replacing the short one first would leave a mangled tail behind. This
    # also orders the doubled spelling before the single one, which matters
    # because the single form is a substring of neither but the sort must be
    # total for the result to be deterministic.
    for spelling, rendered in sorted(pairs, key=lambda p: len(p[0]), reverse=True):
        if spelling in text:
            text = text.replace(spelling, rendered)
    return text
